### ISSUE TITLE
canUseWebP returns false in Firefox 70

### ISSUE THREAD

**Issue by EliteMasterEric** [Horat1us/react-img-webp#5]
Firefox is stated to have officially implemented support for WebP images in Firefox 65, and yet in Firefox 70.0.1 this library fails to detect support.

[A CodeSandbox for demonstration](https://codesandbox.io/s/react-webp-test-kf8rw)

This CodeSandbox displays No on Firefox 70.0.1 but displays Yes on Chrome 78.0.3904.97.

[The release notes for WebP support](https://hacks.mozilla.org/2019/01/firefox-65-webp-flexbox-inspector-new-tooling/)

Not that [this issue also occurs in a similar library](https://github.com/DonRai/react-image-webp/issues/39) indicating that this may be a browser problem.

EDIT: I found a snippet from OurCodeWorld, which I added to the CodeSandbox, which does return the correct response.

**Comment by feruzm** [comment]
So library works as expected?

**Comment by EliteMasterEric** [comment]
> So library works as expected?

@feruzm The library does NOT work as expected. Firefox supports WebP but this library currently returns false.

**Comment by feruzm** [comment]
> > So library works as expected?
> 
> @feruzm The library does NOT work as expected. Firefox supports WebP but this library currently returns false.

I see, got confused with your Edit section thinking issue was with codesandbox not library. Thanks for clarifying!

**Comment by EliteMasterEric** [comment]
The library is not working as expected, and CodeSandbox serves as a
minimally reproducible example.

**Comment by mrnossiom** [comment]
It would be better to change the snippet to the code below because it supports Firefox 65+:

```js
async function WebpIsSupported() {
  // If the browser doesn't has the method createImageBitmap, you can't display webp format
  if (!window.createImageBitmap) return false;

  // Base64 representation of a white point image
  const webpData =
    "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoCAAEAAQAcJaQAA3AA/v3AgAA=";

  // Retrieve the Image in Blob Format
  const blob = await fetch(webpData).then(r => r.blob());

  // If the createImageBitmap method succeeds, return true, otherwise false
  return createImageBitmap(blob).then(() => true, () => false);
}
```

This snippet come from [OurCodeWorld](https://ourcodeworld.com/articles/read/630/how-to-detect-if-the-webp-image-format-is-supported-in-the-browser-with-javascript)
Thanks to @MasterEric

Tell me if it's useful to do a Pull Request... I don't know if this project is abandoned.

**Comment by EliteMasterEric** [comment]
Just quickly checked and on Firefox 110.0.1, the CodeSandbox works. Either this repo or Firefox fixed the issue.
